---
- hosts: localhost
  connection: local
  become: true
  module_defaults:
    copy:
      owner: coba
      group: wheel
    file:
      owner: coba
      group: wheel

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install basic packages
      community.general.pacman:
        name: "{{ lookup('file', 'basic_packages').splitlines() }}"
        state: latest

    - name: Ensure main directories exist
      ansible.builtin.file:
        path: "/home/coba/{{ item.dir }}"
        state: directory
        modification_time: now
        access_time: now
      loop:
        - {dir: .config}
        - {dir: .ssh}
        - {dir: Documentos}
        - {dir: Documentos/Archive}
        - {dir: Documentos/Work}
        - {dir: Documentos/Work/Xebia}
        - {dir: Downloads}
        - {dir: Sync}
        - {dir: Sync/database}

    - name: Setup shell
      block:
      - name: Copy .zshrc
        ansible.builtin.copy:
          src: files/.zshrc
          dest: /home/coba/
      - name: Copy zsh .config
        ansible.builtin.copy:
          src: files/zsh
          dest: /home/coba/.config/
      - name: Change shell to zsh
        ansible.builtin.user:
          name: coba
          shell: /bin/zsh

    - name: Copy kitty conf
      ansible.builtin.copy:
        src: files/kitty
        dest: /home/coba/.config/

    - name: Configure git
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - {name: user.email, value: coba@cobac.eu}
        - {name: user.name, value: David Coba}
        - {name: github.user, value: cobac}
        - {name: init.defaultbranch, value: main}

    - name: Configure ssh for github
      ansible.builtin.blockinfile:
        path: /home/coba/.ssh/config
        create: true
        block: |
          Host github.com
            Hostname ssh.github.com
            User git
            Port 443
            # IdentityFile ~/.ssh/[[ ID NAME ]]

    - name: Setup graphical interface
      import_tasks: graphical/graphical.yml

    - name: install rest of packages
      community.general.pacman:
        name: "{{ lookup('file', 'packages').splitlines() }}"
        state: latest

    - name: Activate syncthing
      ansible.builtin.systemd:
        name: syncthing
        state: started
        enabled: true
        scope: user
      become: yes
      become_user: coba
      become_method: su
      environment: 
        # This is horrible hardcoded
        XDG_RUNTIME_DIR: "/run/user/1000"

    - name: Aur stuff
      import_tasks: aur/aur.yml

    - name: Setup emacs
      import_tasks: emacs/emacs.yml
