---
- hosts: localhost
  connection: local
  become: true
  module_defaults:
    copy:
      owner: coba
      group: wheel
    file:
      owner: coba
      group: wheel

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install basic packages
      community.general.pacman:
        name: "{{ lookup('file', 'basic_packages').splitlines() }}"
        state: latest

    - name: Ensure main directories exist
      ansible.builtin.file:
        path: "/home/coba/{{ item.dir }}"
        state: directory
        modification_time: now
        access_time: now
      loop:
        - {dir: .config}
        - {dir: Documentos}
        - {dir: Documentos/Archive}
        - {dir: Documentos/Work}
        - {dir: Documentos/Work/Xebia}
        - {dir: Downloads}

    - name: Setup graphical interface
      import_tasks: graphical/graphical.yml

    - name: Setup emacs
      import_tasks: emacs/emacs.yml
      

