---
- hosts: localhost
  connection: local
  become: true
  module_defaults:
    copy:
      owner: coba
      group: wheel
    file:
      owner: coba
      group: wheel

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install basic packages
      community.general.pacman:
        name: "{{ lookup('file', 'packages').splitlines() }}"
        state: latest

    - name: Setup emacs
      import_tasks: emacs/emacs.yml
      

