---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Setup emacs
      import_tasks: emacs/emacs.yml
      

