- name: Install graphical packages packages
  community.general.pacman:
    name: "{{ lookup('file', 'graphical_packages').splitlines() }}"
    state: latest

- name: copy xorg files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /home/coba/
  with_items:
    - .xinitrc
    - .xserverrc
    - .Xkeymap-laptop

- name: copy i3 files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /home/coba/.config/
  with_items:
    - i3
    - i3blocks
    - i3status

- name: set es keyboard
  ansible.builtin.command: localectl set-x11-keymap es

- name: add user to video group
  ansible.builtin.user:
    name: coba
    groups: video
    append: yes

- name: Configure trackpad
  # also install libinput gestures
  ansible.builtin.blockinfile:
    path: /etc/X11/xorg.conf.d/30-touchpad.conf
    create: true
    block: |
      Section "InputClass"
        Identifier "Touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "ClickMethod" "clickfinger"
        Option "Tapping" "on"
      EndSection

- name: Configure trackball
  ansible.builtin.blockinfile:
    path: /etc/X11/xorg.conf.d/41-trackball.conf
    create: true
    block: |
      Section "InputClass"
        Identifier "Logitech ERGO M575"
        MatchDriver "libinput"
        MatchProduct "Logitech ERGO M575"
        Option "Accel Profile Enabled" "1 0 0"
        Option "Accel Speed" "1"
      EndSection
